"""Recorded data for the interactive figures, one module per unit: uNN.py (ucapstone.py).

Each module defines data() -> a JSON-able dict computed from the unit's reference solution
or colib. `co viz [NN]` calls it and writes units/<unit>/viz-data.js, which sets
window.VIZ_DATA. It is a classic script, not JSON, because pages opened from file://
cannot fetch sibling files (the same reason glossary.js exists).
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def module_name(unit: Path) -> str:
    key = unit.name.split("-")[0]
    return f"u{key}"


def build(unit: Path) -> Path | None:
    """Write unit/viz-data.js if the unit has a trace module. Returns the path, or None."""
    name = module_name(unit)
    if not (HERE / f"{name}.py").exists():
        return None
    mod = importlib.import_module(f"slides.viz.traces.{name}")
    payload = json.dumps(mod.data(), ensure_ascii=False, separators=(",", ":"))
    out = unit / "viz-data.js"
    js = (f"// Generated by `co viz` from slides/viz/traces/{name}.py; edit that, not this.\n"
          f"window.VIZ_DATA = {payload};\n")
    if not out.exists() or out.read_text() != js:
        out.write_text(js)
    return out
