"""Unit 25 lab — semidefinite relaxations.  REFERENCE SOLUTION, functional.

Most of this unit is linear algebra, which numpy already expresses without mutation: the weight matrix is
one np.bincount over flattened indices, the vectors come from one eigendecomposition, and the expected cut
is a vectorised arccos. The LP constraints are generated by comprehensions, and local search is an unfold over cuts.
"""

from __future__ import annotations

import math
from itertools import chain, combinations, takewhile

import cvxpy as cp
import numpy as np
import toolz as tz

from colib.solvers import highs_lp


# ---------------------------------------------------------------- step 1 ---

def weight_matrix(mc):
    n = mc.n
    rows = [u for u, v in mc.edges] + [v for u, v in mc.edges]
    cols = [v for u, v in mc.edges] + [u for u, v in mc.edges]
    return np.bincount(np.array(rows, int) * n + np.array(cols, int), weights=list(mc.weights) * 2,
                       minlength=n * n).reshape(n, n) if mc.edges else np.zeros((n, n))


def maxcut_sdp(mc):
    X = cp.Variable((mc.n, mc.n), PSD=True)
    problem = cp.Problem(cp.Maximize(cp.sum(cp.multiply(weight_matrix(mc), 1 - X)) / 4), [cp.diag(X) == 1])
    problem.solve(solver="CLARABEL")
    return float(problem.value), np.array(X.value)


def vectors_from_gram(X):
    vals, vecs = np.linalg.eigh((X + X.T) / 2)
    V = vecs * np.sqrt(np.clip(vals, 0, None))
    return V / np.linalg.norm(V, axis=1, keepdims=True)


# ---------------------------------------------------------------- step 2 ---

def hyperplane_round(V, rng):
    return [int(s >= 0) for s in (V @ rng.standard_normal(V.shape[1]))]


def expected_cut(mc, V):
    if not mc.edges:
        return 0.0
    us, vs = (np.array(side) for side in zip(*mc.edges))
    cosines = np.clip(np.einsum("ij,ij->i", V[us], V[vs]), -1, 1)
    return float(np.dot(mc.weights, np.arccos(cosines)) / math.pi)


def gw_constant(grid=100_000):
    ratio = lambda t: (t / math.pi) / ((1 - math.cos(t)) / 2)
    _, t0 = min((ratio(math.pi * k / grid), math.pi * k / grid) for k in range(1, grid + 1))
    g = (math.sqrt(5) - 1) / 2

    def shrink(bracket):
        lo, hi = bracket
        a, b = hi - g * (hi - lo), lo + g * (hi - lo)
        return (lo, b) if ratio(a) < ratio(b) else (a, hi)

    lo, hi = tz.nth(60, tz.iterate(shrink, (t0 - math.pi / grid, min(math.pi, t0 + math.pi / grid))))
    t = (lo + hi) / 2
    return ratio(t), t


# ---------------------------------------------------------------- step 3 ---

def maxcut_edge_lp(mc):
    n, m = mc.n, len(mc.edges)
    unit_row = lambda entries: [entries.get(k, 0.0) for k in range(n + m)]
    rows = list(chain.from_iterable(
        ((unit_row({n + k: 1, u: -1, v: -1}), 0), (unit_row({n + k: 1, u: 1, v: 1}), 2))
        for k, (u, v) in enumerate(mc.edges)))
    A, b = zip(*rows)
    return highs_lp(list(A), list(b), [0.0] * n + list(mc.weights), sense="max", upper=1.0).value


def maxcut_triangle_lp(mc):
    pairs = list(combinations(range(mc.n), 2))
    index = {p: k for k, p in enumerate(pairs)}
    patterns = (((1, 1, 1), 2), ((1, -1, -1), 0), ((-1, 1, -1), 0), ((-1, -1, 1), 0))
    rows = [([dict(zip((index[(i, j)], index[(j, k)], index[(i, k)]), coeffs)).get(p, 0.0) for p in range(len(pairs))], rhs)
            for i, j, k in combinations(range(mc.n), 3) for coeffs, rhs in patterns]
    weight_of = tz.reduceby(lambda e: index[tuple(sorted(e[0]))], lambda acc, e: acc + e[1], zip(mc.edges, mc.weights), 0)
    c = [float(weight_of.get(p, 0)) for p in range(len(pairs))]
    if not rows:
        return float(sum(mc.weights))
    A, b = zip(*rows)
    return highs_lp(list(A), list(b), c, sense="max", upper=1.0).value


# ---------------------------------------------------------------- step 4 ---

def lovasz_theta(n, edges):
    X = cp.Variable((n, n), PSD=True)
    problem = cp.Problem(cp.Maximize(cp.sum(X)), [cp.trace(X) == 1] + [X[u, v] == 0 for u, v in edges])
    problem.solve(solver="CLARABEL")
    return float(problem.value)


def complement(n, edges):
    present = frozenset(tuple(sorted(e)) for e in edges)
    return [p for p in combinations(range(n), 2) if p not in present]


# ---------------------------------------------------------------- step 5 ---

def local_search(mc, x):
    adj = tz.groupby(0, chain(((u, (v, w)) for (u, v), w in zip(mc.edges, mc.weights)),
                              ((v, (u, w)) for (u, v), w in zip(mc.edges, mc.weights))))
    gain = lambda cut, v: sum(w if cut[u] == cut[v] else -w for _, (u, w) in adj.get(v, []))

    def step(cut):
        v = next((v for v in range(mc.n) if gain(cut, v) > 0), None)
        return None if v is None else cut[:v] + (1 - cut[v],) + cut[v + 1:]

    states = tz.iterate(lambda c: c if c is None else step(c), tuple(x))
    return list(tz.last(takewhile(lambda c: c is not None, states)))


def goemans_williamson(mc, rounds, rng):
    value, X = maxcut_sdp(mc)
    V = vectors_from_gram(X)
    cuts = [hyperplane_round(V, rng) for _ in range(rounds)]
    best = max(cuts, key=mc.objective)
    return best, mc.objective(best), value
